name: Daily GitHub Trending Scraper

# This grants the workflow the necessary permissions to write back to the repo.
permissions:
  contents: write
# ------------------------------------

# test
on:
  # Run this workflow automatically every day at 1 AM UTC
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_run_scraper:
    runs-on: ubuntu-latest

    # Set environment variables for the job
    env:
      TARGET_LANGUAGE: java # You can change "java" to "python", "typescript", etc.
      TARGET_TIMEFRAME: daily # Options: daily, weekly, monthly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        # This step is important for CI environments
        run: chmod +x ./gradlew

      - name: Build with Gradle
        # This command builds the project and creates the runnable JAR
        run: ./gradlew build

      - name: Run the Java application
        # Gradle usually puts the JAR in build/libs/
        run: java -jar build/libs/app.jar

      - name: Commit and push the generated file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Docs: Update daily trending repositories report"
          file_pattern: "*.md"

  # --- TO SEND A SLACK NOTIFICATION ---
  send-slack-notification:
    runs-on: ubuntu-latest
    needs: build_and_run_scraper # This ensures this job only runs AFTER the scraper job
    if: success() # And only if the scraper job was successful
    steps:
      - name: Send Slack Notification on Success
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This is the ID of the channel or user you want to message
          # For a public channel: C024BE91L
          # For a direct message to yourself: U024BE7LH (your Member ID)
          channel-id: 'C09K5U3QHPB'
          # This is the message that will be sent
          slack-message: "✅ GitHub scraper ran successfully! View the latest report: ${{ github.server_url }}/${{ github.repository }}/blob/main/TRENDING.md"
        env:
          # You MUST create a secret in your repository called SLACK_BOT_TOKEN
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}