name: Daily GitHub Trending Scraper

on:
  # Run this workflow automatically every day at 1 AM UTC
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_run_scraper:
    runs-on: ubuntu-latest

    # Set environment variables for the job
    env:
      TARGET_LANGUAGE: java # You can change "java" to "python", "typescript", etc.
      TARGET_TIMEFRAME: daily # Options: daily, weekly, monthly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        # This step is important for CI environments
        run: chmod +x ./gradlew

      - name: Build with Gradle
        # This command builds the project and creates the runnable JAR
        run: ./gradlew build

      - name: Run the Java application
        # Gradle usually puts the JAR in build/libs/
        run: java -jar build/libs/app.jar

      - name: Commit and push the generated file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Docs: Update daily trending repositories report"
          file_pattern: "*.md"